config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users

  #* use the following lines or change link_to to button_to for sign out
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :friends
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  # has_many :friends, class_name: "friend", foreign_key: "reference_id"
  has_many :friends

  VALID_STATUSES = %w[public private archived]

  validates :state, inclusion: { in: VALID_STATUSES }

  def archived?
    state == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit destroy update]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html do
          redirect_to friend_url(@friend),
                      notice: 'Friend was successfully created.'
        end
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @friend.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html do
          redirect_to friend_url(@friend),
                      notice: 'Friend was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @friend.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html do
        redirect_to friends_url, alert: "#{@friend.first_name} is deleted."
      end
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    if @friend.nil?
      redirect_to friends_path,
                  alert: 'You are not authorized to modify this friend'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params
      .require(:friend)
      .permit(
        :first_name,
        :last_name,
        :email,
        :phone,
        :instagram_id,
        :user_id,
        :state,
      )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control", placeholder:'name@example.com' %>
  </div>

  <div class="form-group">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :instagram_id, style: "display: block" %>
    <%= form.text_field :instagram_id, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :state, style: "display: block" %>
    <%= form.select :state,  ['public', 'private', 'archived'], selected: 'private', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: "hidden", class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="jumbotron">
  <h1 class="display-4">
    <%= friend.first_name %> 
    <%= friend.last_name %>
  </h1>
  <p class="lead">
    <%= friend.email %> |
    <%= friend.phone %> |
    @<%= friend.instagram_id %>
  </p>
  <hr class="my-4">
  <div>
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:'btn btn-outline-info' %>
    <%= link_to "Back to friends", friends_path, class:'btn btn-outline-secondary' %>
    <%= button_to "Delete #{friend.first_name}", @friend, method: :delete, class: "btn btn-outline-danger mt-2"%>
  </div>
</div>

app/views/friends/_friend_table.html.erb
<h1>
  Friends List
  <span class="mx-1 position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger text-light">
    <%= current_user.friends.count %>
  </span>
</h1>

<br/>

<table class="table table-dark table-striped table-hover ">
 <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Instagram</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
      <tr>
        <td> <%= link_to friend.first_name + ' ' + friend.last_name, friend, class:'text-light' %></td>
        <td> <%= friend.email %></td>
        <td> <%= friend.phone %></td>
        <td> <%= friend.instagram_id %></td>

        <td> <%= link_to "Edit", edit_friend_path(friend), class:'btn btn-outline-info btn-sm' %></td>
        <td> <%= button_to "Delete", friend, method: :delete, class: "btn btn-outline-danger  btn-sm"%></td>
      </tr>
    <%end %>
  <%end %>
  </tbody>
</table>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br/>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend , class: "btn btn-dark"%>
  <%= link_to "Back to friends", friends_path, class: "btn btn-outline-dark"%>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
  <%= render "friend_table", friend: @friend %> 
  <%= link_to "Add New friend", new_friend_path, class:'btn btn-success' %>
  <%= render 'layouts/footer' %>
<% else %>
  <h1>Welcome!</h1>
  <p>You have to login to access the friends table</p>
  <%= link_to "Log in", new_user_session_path, class:'btn btn-primary' %>
<% end %>

    <%
=begin%>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend, class:'btn btn-outline-info' %>
    </p>
    <br> 
  <% end %>
</div>

<%
=end%>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>

<%= render "form", friend: @friend %>
<br>
<%= link_to "Back to friends", friends_path, class:'btn btn-outline-secondary' %>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
 
  <%
=begin%>
 <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger"%> 
<%
=end%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friends App", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mfe-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Friends</a>
          <ul class="dropdown-menu bg-dark">
            <li><%= link_to "Add Friend", new_friend_path, class:'nav-link pl-3'%></li>
            <li><%= link_to "Friends List", friends_path, class:'nav-link pl-3'%></li>
          </ul>
        </li>

          <li>
            <%= link_to "About", home_about_path, class:'nav-link' %> 
          </li>

        <% if user_signed_in? %>
          <li class='ml-5'>
            <%= link_to "Edit Profile", edit_user_registration_path, class:'nav-link' %> 
          </li>
          <li>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:'btn btn-outline-danger btn-sm my-1 mx-1' %> 
          </li>
        <% else %>
          <li class='ml-5'>
            <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %> 
          </li>

          <li>
            <%= link_to "Login", new_user_session_path, class:'nav-link' %> 
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/home/about.html.erb
<h1 class="card bg-warning"> About us</h1>

app/views/home/index.html.erb
<%
=begin%>
 <div id = 'root' data-controller = 'react'></div> 
<%
=end%>
<%= content_tag(:div, "", id: "root", data: { controller: "react"})%>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<%
=begin%>
 
<div class="alert alert-primary d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 mr-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
  <div>
    <%= notice %>
  </div>
</div> 
<%
=end%>

<% if notice %>
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 mr-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    <%= flash.notice %>
  </div>
</div>
<% end %>

<% if alert %>
<div class="alert alert-warning d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 mr-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#info-fill"/></svg>
  <div>
    <%= alert %>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination mt-5">
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <li class="page-item active"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item">
      <a class="page-link" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    <title>Friends App</title>

  </head>
  <body>
    <%=  render 'home/header' %>
    <div class="container mt-3">
      <% if notice || alert %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <br />
      <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>